### ISSUE TITLE
Padding example error message

### ISSUE THREAD

**Issue by thealgebraist** [janestreet/ppx_string#4]
When running the example code:

`[%string "%{col1#Int:term_width / 2}%{col2#:term_width/4}#{col3#:8}#{col4}"]`

I get the following error:

`Error: Invalid literal 2.to_string`

**Comment by v-gb** [comment]
What version of `ppx_string` are you using? I'm pretty sure it doesn't support the padding syntax because it's too old. If you upgrade, then I suspect that either:
- the example will work (or give type errors like "col1 is unbound")
- or you will get a different error, something like `invalid %{} expression: ...`, if the ppx is still too old

(If the latter, it's possible that there's no opam release contain this ppx_string change. If that was the case, then you'd need to either wait for a release or fiddle with opam to use the bleeding edge, which is possible but is beyond my understanding).
